module.exports = {
  chapterService: require('./chapterService'),
  commentService: require('./commentService'),
  eventService: require('./eventService'),
  likeService: require('./likeService'),
  messageService: require('./messageService'),
  notificationService: require('./notificationService'),
  organizationService: require('./organizationService'),
  organizationAccountService: require('./organizationAccountService'),
  permissionService: require('./permissionService'),
  postService: require('./postService'),
  roleService: require('./roleService'),
  rolePermissionService: require('./rolePermissionService'),
  memberService: require('./memberService'),
  memberAccountService: require('./memberAccountService'),
  chapterAccountService: require('./chapterAccountService'),
  friendshipService: require('./friendshipService'),
  tagService: require('./tagService'),
  accountService: require('./accountService'),
};
